### ISSUE TITLE
ENOENT: no such file or directory, open './package-lock.json'

### ISSUE THREAD

**Issue by w3cj** [Sila-Money/sila-sdk#15] opened 2020-11-11 17:00 UTC
I got the following error when attempting to update to the latest rc:

```
> sila-sdk@0.2.13-rc.0 preinstall /path/to/node_modules/sila-sdk
> npx npm-force-resolutions

npx: installed 5 in 1.563s
ENOENT: no such file or directory, open './package-lock.json'
```

This issue is discussed in the `npm-force-resolutions` repo: https://github.com/rogeriochaves/npm-force-resolutions/issues/10

**Comment by chrisbra-riftpay** [comment] 2020-11-20 22:39
Same issue here

**Comment by chepix10** [comment] 2020-11-24 23:38
Hi @w3cj @chrisbra-riftpay We'll be addressing this on 0.2.13-rc.1

**Comment by chepix10** [comment] 2020-11-25 01:03
This was fixed on #16. Can you try again with version 0.2.13-rc.1?

**Comment by chrisbra-riftpay** [comment] 2020-11-25 12:52
That seemed to fix the issue.
Note there was an error with a sub module you are using, as long as it doesn't break our process it seems to be a low level issue.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'rebuild' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prerebuild', 'rebuild', 'postrebuild' ]
5 info lifecycle secp256k1@3.7.1~prerebuild: secp256k1@3.7.1
6 info lifecycle secp256k1@3.7.1~rebuild: secp256k1@3.7.1
7 verbose lifecycle secp256k1@3.7.1~rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle secp256k1@3.7.1~rebuild: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-
10 silly lifecycle secp256k1@3.7.1~rebuild: Args: [ '-c', 'node-gyp rebuild' ]
11 silly lifecycle secp256k1@3.7.1~rebuild: Returned: code: 1  signal: null
12 info lifecycle secp256k1@3.7.1~rebuild: Failed to exec rebuild script
13 verbose stack Error: secp256k1@3.7.1 rebuild: `node-gyp rebuild`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid secp256k1@3.7.1
15 verbose cwd ********************************/node_modules/eccrypto/node_modules/secp256k1
16 verbose Linux 5.4.0-53-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "rebuild"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error secp256k1@3.7.1 rebuild: `node-gyp rebuild`
22 error Exit status 1
23 error Failed at the secp256k1@3.7.1 rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by chrisbra-riftpay** [comment] 2020-11-25 13:09
Update, looks like that issue went away when I rebuilt the package. This can be marked as solved from our end

**Comment by chrisbra-riftpay** [comment] 2020-11-25 13:40
After effects does indeed break a process it appears.
After configuring using two ways
```
1st;
Sila.configure({ 
			handle: this.configService.get<string>('SILA_HANDLE'), 
			key: this.configService.get<string>('SILA_KEY') 
});
2nd;
Sila.configure({ 
			handle: this.configService.get<string>('SILA_HANDLE'), 
			key: this.configService.get<string>('SILA_KEY') 
});
Sila.setEnvironment('prod');
Sila.enableSandbox();
```
This issue prevails
```
secp256k1 unavailable, reverting to browser version
/home/chris/Desktop/central-api/central-api/node_modules/sila-sdk/lib/index.js:953
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(userHandle, userPrivateKey, document) {
                                             ^

ReferenceError: regeneratorRuntime is not defined
    at /home/****************************************/node_modules/sila-sdk/lib/index.js:953:46
    at Object.<anonymous> (/home/****************************************/node_modules/sila-sdk/lib/index.js:987:2)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/****************************************/dist/sila/sila.service.js:15:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/****************************************/dist/user/user.controller.js:19:24)

```

**Comment by chrisbra-riftpay** [comment] 2020-11-25 13:41
After effects does indeed break a process it appears.
After configuring using two ways
```
1st;
Sila.configure({ 
			handle: this.configService.get<string>('SILA_HANDLE'), 
			key: this.configService.get<string>('SILA_KEY') 
});
2nd;
Sila.configure({ 
			handle: this.configService.get<string>('SILA_HANDLE'), 
			key: this.configService.get<string>('SILA_KEY') 
});
Sila.setEnvironment('prod');
Sila.enableSandbox();
```
This issue prevails
```
secp256k1 unavailable, reverting to browser version
/home/****************************************/node_modules/sila-sdk/lib/index.js:953
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(userHandle, userPrivateKey, document) {
                                             ^

ReferenceError: regeneratorRuntime is not defined
    at /home/****************************************/node_modules/sila-sdk/lib/index.js:953:46
    at Object.<anonymous> (/home/****************************************/node_modules/sila-sdk/lib/index.js:987:2)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/****************************************/dist/sila/sila.service.js:15:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/****************************************/dist/user/user.controller.js:19:24)

```

**Comment by chepix10** [comment] 2020-11-25 13:50
@chrisbra-riftpay Does this happens on a specific endpoint or for the hole ussage of the SDK?

**Comment by chrisbra-riftpay** [comment] 2020-11-25 14:27
The whole usage.
We blocked everything implementing sila and just left the import statement and the issue is there.

**Comment by chrisbra-riftpay** [comment] 2020-11-25 14:31
I tried diving into the runtimeGenerator function. I don't see it in the source code but see it in the compiled code. I don't use pure js much, mostly typescript so I don't know how/why that function is being defined when it is not in the source.

**Comment by chepix10** [comment] 2020-11-25 14:31
Can you try this:
- Install regenerator runtime
`npm i -S regeneratior-runtime`
- Import it to the project where your importing sila
```
// CommonJS
require("regenerator-runtime/runtime");
 
// ECMAScript 2015
import "regenerator-runtime/runtime";
```

**Comment by chrisbra-riftpay** [comment] 2020-11-25 14:33
That does the trick.
Typo ***
```
npm i -S regenerator-runtime
```

**Comment by chepix10** [comment] 2020-11-25 14:34
Thanks for catching the typo. We'll address this on 0.2.13-rc.2 so you don't have to import it manually.

**Comment by chepix10** [comment] 2020-11-25 15:12
PR #17 has been merged and published to NPM. You can give it a go to v0.2.13-rc.2

**Closed** 2020-12-16 16:51 UTC
